In [1]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [2]:
arr1=np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
ser1 =  Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [12]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
pd.concat([ser1,ser2],axis=1,join_axes=[['U','V','Y']])

0    1
U  1.0  NaN
V  2.0  NaN
Y  NaN  4.0

In [14]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [15]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.614550 -0.139032  0.004831
1       NaN -1.701178  2.432096  2.195827
2       NaN  0.759442  0.663846  0.193536
3       NaN -0.084854  3.380143  0.290299
0 -0.414560  2.056980  1.912200       NaN
1 -1.139628  0.781124 -0.865026       NaN
2 -0.563533  1.206514  0.277583       NaN

In [16]:
pd.concat([dframe1,dframe2],axis=1)

X         Y         Z         Y         Q         X
0 -0.614550 -0.139032  0.004831  1.912200 -0.414560  2.056980
1 -1.701178  2.432096  2.195827 -0.865026 -1.139628  0.781124
2  0.759442  0.663846  0.193536  0.277583 -0.563533  1.206514
3 -0.084854  3.380143  0.290299       NaN       NaN       NaN

In [17]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -0.614550 -0.139032  0.004831
1       NaN -1.701178  2.432096  2.195827
2       NaN  0.759442  0.663846  0.193536
3       NaN -0.084854  3.380143  0.290299
4 -0.414560  2.056980  1.912200       NaN
5 -1.139628  0.781124 -0.865026       NaN
6 -0.563533  1.206514  0.277583       NaN